### ISSUE TITLE
Add void to LineData's NON_PASCAL_TYPES

### ISSUE THREAD

**Issue by jcommander** [TheDuriel/MagicMacros#14]
I guess title is self-explanatory, I think a PR is overkill

First thing I tried was creating a void using the func|fnc Macro which will just turn into the default "type"
Extending `LineData;gd:8`->`NON_PASCAL_TYPES` by void would fix this
`const NON_PASCAL_TYPES: Array[String] = ["void", "bool", "float", "int"]`

At first glance I see no reason why this would be left out

**Comment by TheDuriel** [comment]
Definite oversight. Pushing a fix!

**Comment by TheDuriel** [comment]
Fixed in 082a65527d4ec2ae2f101868527c6cf67e403031

**Comment by TheDuriel** [comment]
Thanks a bunch!

**Comment by jcommander** [comment]
Wow, congrats on that amazing response time!
Thanks to you too 🎉
