### ISSUE TITLE
Cannot call method 'is_visible_in_tree' on a null value.

### ISSUE THREAD

**Issue by Bimbam360** [TheDuriel/MagicMacros#2]
Just installed, but seeing this spammed a lot in output:

res://addons/MagicMacros/MagicMacros.gd:51 - Cannot call method 'is_visible_in_tree' on a null value.

My bootleg workaround that seems to get things semi working (no idea what impact this may have elsewhere though:
![image](https://github.com/user-attachments/assets/b50bd5ce-cc32-4b72-9d21-064663ba6874)

**Comment by TheDuriel** [comment]
Yup, missing guard clause! Thanks for catching.
