### ISSUE TITLE
Plugins in 4.4.dev3, not working

### ISSUE THREAD

**Issue by yvchenzhang** [TheDuriel/MagicMacros#5]
Change the signal connection to editor_script_changed, and the plugin will work
old: EditorInterface.get_script_editor().script_changed.connect(_on_script_changed)
new: EditorInterface.get_script_editor().editor_script_changed.connect(_on_script_changed)

**Comment by TheDuriel** [comment]
I will make the change once 4.4 releases, thank you for documenting it here!

**Comment by RiOnE03** [comment]
This change is needed for 4.3 as well.

**Comment by TheDuriel** [comment]
I saw the error on my part earlier. Working through one of the PRs at the moment which includes it!

**Comment by TheDuriel** [comment]
fixed in 86b654b6e6e7b6a1551c84681d585ac7af969125
